[package]
name = "query-api"
version = "0.1.0"
authors = ["Markus Stange <mstange@themasta.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[dependencies]
samply-api = { path = "../../samply-api" }
clap = { version = "4", features = ["derive"] }
memmap2 = "0.9.4"
anyhow = "1.0.83"
futures = "0.3.5"
serde_json = "1.0.117"
