[package]
name = "fxprof-processed-profile"
version = "0.8.1"
edition = "2021"
rust-version = "1.63" # needed by indexmap
authors = ["Markus Stange <mstange.moz@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Create profiles in the Firefox Profiler's processed profile JSON format."
repository = "https://github.com/mstange/samply/"
readme = "README.md"

[dependencies]
bitflags = "2.10"
debugid = "0.8.0"
rustc-hash = "2"
indexmap = "2.7"
hashbrown = "0.17"
struson = "0.7"
elsa = "1.11"
json-slabs = "0.1.0"

[dev-dependencies]
insta = { version = "1.48", features = ["json"] }
serde_json = "1.0"
