use std::borrow::Cow;

use crate::error::Error;
use crate::sans_io::{LoadStep, NeedsFiles};
use crate::shared::{FileContents, FileLoadError, FileLocation, FileTypes};
use crate::{generation::SymbolMapGeneration, mapped_path::UnparsedMappedPath};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct SourceFilePathIndex(pub u32);

/// A handle for a [`SourceFilePath`]. Can be resolved with the symbol map.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct SourceFilePathHandle {
    pub(crate) generation: SymbolMapGeneration,
    pub(crate) index: SourceFilePathIndex,
}

/// The path of a source file, as found in the debug info.
///
/// This contains both the raw path and an optional "mapped path". The raw path can
/// refer to a file on this machine or on a different machine (i.e. the original
/// build machine). The mapped path is something like a permalink which potentially
/// allows obtaining the source file from a source server or a public hosted repository.
#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub enum SourceFilePath<'a> {
    RawPath(Cow<'a, str>),
    BreakpadSpecialPathStr(Cow<'a, str>),
    RawPathAndUrl(Cow<'a, str>, Cow<'a, str>),
}

impl<'a> SourceFilePath<'a> {
    /// A short, display-friendly version of this path.
    pub fn display_path(&self) -> Cow<'_, str> {
        if let Some(display_path) = self.mapped_path().display_path() {
            let display_path = display_path.to_string();
            return display_path.into();
        }
        Cow::Borrowed(self.raw_path())
    }

    pub fn to_owned(&self) -> SourceFilePath<'static> {
        match self {
            Self::RawPath(r) => SourceFilePath::RawPath(r.as_ref().to_owned().into()),
            Self::BreakpadSpecialPathStr(bsp) => {
                SourceFilePath::BreakpadSpecialPathStr(bsp.as_ref().to_owned().into())
            }
            Self::RawPathAndUrl(r, u) => SourceFilePath::RawPathAndUrl(
                r.as_ref().to_owned().into(),
                u.as_ref().to_owned().into(),
            ),
        }
    }

    pub fn special_path_str(&self) -> Option<Cow<'_, str>> {
        if let Self::BreakpadSpecialPathStr(bsp) = self {
            return Some(Cow::Borrowed(bsp));
        }
        if let Some(bsp) = self.mapped_path().special_path_str() {
            let bsp = bsp.to_string();
            return Some(bsp.into());
        }
        None
    }

    /// The raw path to the source file, as written down in the debug file. This is
    /// usually an absolute path.
    ///
    /// Examples:
    ///
    ///  - `"/Users/mstange/code/samply/samply-symbols/src/shared.rs"`
    ///  - `"/Users/mstange/code/mozilla/widget/cocoa/nsNativeThemeCocoa.mm"`
    ///  - `"./csu/../csu/libc-start.c"`
    ///  - `"/rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ptr/const_ptr.rs"`
    ///  - `r#"D:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl"#`
    ///
    /// If the debug file was produced by compiling code on this machine, then the path
    /// usually refers to a file on this machine. (An exception to this is debug info
    /// from the Rust stdlib, which has fake `/rustc/<rev>/...` paths even if the when
    /// compiling Rust code locally.)
    ///
    /// If the code was compiled on a different machine, then the raw path does not refer
    /// to a file on this machine.
    ///
    /// Sometimes this path is a relative path. One such case was observed when the
    /// "debug file" was a synthetic .so file which was generated by `perf inject --jit`
    /// based on a JITDUMP file which included relative paths. You could argue
    /// that the application which emitted relative paths into the JITDUMP file was
    /// creating bad data and should have written out absolute paths. However, the `perf`
    /// infrastructure worked fine on this file, because the relative paths happened to
    /// be relative to the working directory, and because perf / objdump were resolving
    /// those relative paths relative to the current working directory.
    pub fn raw_path(&self) -> &str {
        match self {
            SourceFilePath::RawPath(raw) => raw,
            SourceFilePath::BreakpadSpecialPathStr(bsp) => bsp, // is this ok?
            SourceFilePath::RawPathAndUrl(raw, _) => raw,
        }
    }

    /// Returns the raw path while consuming this `SourceFilePath`.
    pub fn into_raw_path(self) -> Cow<'a, str> {
        match self {
            SourceFilePath::RawPath(raw) => raw,
            SourceFilePath::BreakpadSpecialPathStr(bsp) => bsp, // is this ok?
            SourceFilePath::RawPathAndUrl(raw, _) => raw,
        }
    }

    /// A variant of the path which may allow obtaining the source code for this file
    /// from the web. The return value
    ///
    /// Examples:
    ///
    ///   - If the source file is from a Rust dependency from crates.io, we detect the
    ///     cargo cache directory in the raw path and create a mapped path of the form [`MappedPath::Cargo`](super::mapped_path::MappedPath::Cargo).
    ///   - If the source file can be obtained from a github URL, and we know this either
    ///     from the `srcsrv` stream of a PDB file or because we recognize a path of the
    ///     form `/rustc/<rust-revision>/`, then we create a mapped path of the form [`MappedPath::Git`](super::mapped_path::MappedPath::Git).
    pub fn mapped_path(&self) -> UnparsedMappedPath<'_> {
        match self {
            SourceFilePath::RawPath(raw) => UnparsedMappedPath::RawPath(raw.clone()),
            SourceFilePath::BreakpadSpecialPathStr(bsp) => {
                UnparsedMappedPath::BreakpadSpecialPath(bsp.clone())
            }
            SourceFilePath::RawPathAndUrl(_, url) => UnparsedMappedPath::Url(url.clone()),
        }
    }
}

impl SymbolMapGeneration {
    pub fn source_file_handle(&self, index: SourceFilePathIndex) -> SourceFilePathHandle {
        SourceFilePathHandle {
            generation: *self,
            index,
        }
    }

    pub fn unwrap_source_file_index(&self, handle: SourceFilePathHandle) -> SourceFilePathIndex {
        assert_eq!(
            handle.generation, *self,
            "SourceFilePathHandle from wrong symbol map used"
        );
        handle.index
    }
}

/// State machine that fetches a single source file and decodes it into a `String`.
///
/// Mirrors `SymbolManager::load_source_file` without performing any I/O.
pub struct LoadSourceFile<FT: FileTypes> {
    state: LoadSourceFileState<FT>,
}

enum LoadSourceFileState<FT: FileTypes> {
    NeedFile { location: FT::FL },
    Done(Result<String, Error>),
    Poisoned,
}

impl<FT: FileTypes> LoadSourceFile<FT> {
    pub fn new(
        debug_file_location: &FT::FL,
        source_file_path: &SourceFilePath<'_>,
    ) -> Result<Self, Error> {
        let location = debug_file_location
            .location_for_source_file(source_file_path.raw_path())
            .ok_or(Error::FileLocationRefusedSourceFileLocation)?;
        Ok(Self {
            state: LoadSourceFileState::NeedFile { location },
        })
    }

    pub fn finish(self) -> Result<String, Error> {
        match self.state {
            LoadSourceFileState::Done(result) => result,
            _ => panic!("LoadSourceFile::finish called before reaching Done"),
        }
    }
}

impl<FT: FileTypes> NeedsFiles<FT> for LoadSourceFile<FT> {
    fn poll(&self) -> LoadStep<'_, FT::FL> {
        match &self.state {
            LoadSourceFileState::NeedFile { location } => LoadStep::NeedFile {
                location,
                required: true,
            },
            LoadSourceFileState::Done(_) => LoadStep::Done,
            LoadSourceFileState::Poisoned => unreachable!("invalid LoadSourceFile state"),
        }
    }

    fn provide(&mut self, result: Result<FT::F, FileLoadError>) {
        let location = match std::mem::replace(&mut self.state, LoadSourceFileState::Poisoned) {
            LoadSourceFileState::NeedFile { location } => location,
            _ => panic!("LoadSourceFile::provide called when not awaiting a file"),
        };
        let decoded = match result {
            Ok(file) => decode_source_file(&location, file),
            Err(e) => Err(Error::OpenFile(location.to_string(), e)),
        };
        self.state = LoadSourceFileState::Done(decoded);
    }
}

fn decode_source_file<FL: FileLocation, F: FileContents>(
    location: &FL,
    file: F,
) -> Result<String, Error> {
    let len = file.len();
    let bytes = file
        .read_bytes_at(0, len)
        .map_err(|e| Error::FileReading(location.to_string(), e))?;
    Ok(String::from_utf8_lossy(bytes).to_string())
}

#[cfg(test)]
mod tests {
    use std::borrow::Cow;

    use super::*;
    use crate::shared::FileTypes;

    /// A `FileTypes` that never actually does any I/O — its only
    /// purpose is to give `LoadSourceFile` something to be generic over so
    /// that the sans-IO loop can be driven from a synchronous test.
    struct TestFileTypes;

    #[derive(Clone, Debug, PartialEq, Eq)]
    struct StringPath(String);

    impl std::fmt::Display for StringPath {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_str(&self.0)
        }
    }

    impl FileLocation for StringPath {
        fn location_for_dyld_subcache(&self, _: &str) -> Option<Self> {
            None
        }
        fn location_for_external_object_file(&self, p: &str) -> Option<Self> {
            Some(StringPath(p.to_owned()))
        }
        fn location_for_pdb_from_binary(&self, p: &str) -> Option<Self> {
            Some(StringPath(p.to_owned()))
        }
        fn location_for_source_file(&self, p: &str) -> Option<Self> {
            Some(StringPath(p.to_owned()))
        }
        fn location_for_breakpad_symindex(&self) -> Option<Self> {
            None
        }
        fn location_for_dwo(&self, _: &str, _: &str) -> Option<Self> {
            None
        }
        fn location_for_dwp(&self) -> Option<Self> {
            None
        }
    }

    impl FileTypes for TestFileTypes {
        type F = Vec<u8>;
        type FL = StringPath;
    }

    #[test]
    fn drives_synchronously_without_async_runtime() {
        let debug_loc = StringPath("/some/debug/file".to_owned());
        let src_path = SourceFilePath::RawPath(Cow::Borrowed("/source/file.rs"));
        let mut sm = LoadSourceFile::<TestFileTypes>::new(&debug_loc, &src_path).unwrap();

        // First poll: a NeedFile with the resolved location.
        match sm.poll() {
            LoadStep::NeedFile { location, required } => {
                assert!(required);
                assert_eq!(location.0, "/source/file.rs");
            }
            _ => panic!("expected NeedFile"),
        }

        // Synthesize file contents — no async involved.
        sm.provide(Ok(b"hello sans-io\n".to_vec()));

        // Second poll: Done.
        assert!(matches!(sm.poll(), LoadStep::Done));
        assert_eq!(sm.finish().unwrap(), "hello sans-io\n");
    }

    #[test]
    fn surfaces_helper_error_on_required_fetch() {
        let debug_loc = StringPath("/some/debug/file".to_owned());
        let src_path = SourceFilePath::RawPath(Cow::Borrowed("/source/missing.rs"));
        let mut sm = LoadSourceFile::<TestFileTypes>::new(&debug_loc, &src_path).unwrap();

        assert!(matches!(sm.poll(), LoadStep::NeedFile { .. }));
        sm.provide(Err("nope".into()));
        assert!(matches!(sm.poll(), LoadStep::Done));
        let err = sm.finish().unwrap_err();
        assert!(matches!(err, Error::OpenFile(_, _)));
    }
}
